### ISSUE TITLE
Unclear information in date column of galnovae.txt

### ISSUE THREAD

**Issue by aaguasca** [Bill-Gray/galnovae#5]
I noticed that some novae display strange words in the date column. 

These are the novae:

1).
https://github.com/Bill-Gray/galnovae/blob/773d675697459793c163d16210b8e5a8fe3c924b/galnovae.txt#L280
2).
https://github.com/Bill-Gray/galnovae/blob/773d675697459793c163d16210b8e5a8fe3c924b/galnovae.txt#L285
3).
https://github.com/Bill-Gray/galnovae/blob/773d675697459793c163d16210b8e5a8fe3c924b/galnovae.txt#L303
4).
https://github.com/Bill-Gray/galnovae/blob/773d675697459793c163d16210b8e5a8fe3c924b/galnovae.txt#L388
5).
https://github.com/Bill-Gray/galnovae/blob/773d675697459793c163d16210b8e5a8fe3c924b/galnovae.txt#L412
6).
https://github.com/Bill-Gray/galnovae/blob/773d675697459793c163d16210b8e5a8fe3c924b/galnovae.txt#L432
7).
https://github.com/Bill-Gray/galnovae/blob/773d675697459793c163d16210b8e5a8fe3c924b/galnovae.txt#L509
8).
https://github.com/Bill-Gray/galnovae/blob/773d675697459793c163d16210b8e5a8fe3c924b/galnovae.txt#L520

I observe this information is inherent in the CBAT List of Novae. Also, some information appears in the OBSCURE XID column as well (novae with numbers listed here 2, 6, 7). On the other hand, some others are not straightforward (at least to me) like in 1, 4, and 8.

Have you considered removing this information? If you want, I can take care of this through a Pull Request. However, I would like to know what information wants to be preserved before moving forward.

**Comment by Bill-Gray** [comment]
Ah,  interesting...

Most of these seem easy enough to clear up,  without actually losing any information.   In order : 

N Sct 1981 turned out not to exist.  ,  for example,  is labelled as "not" a nova,  but the N?? classification should make that clear enough.    "X-1" and "X-4" are redundant,  since the "obscure cross-ID" tells you that anyway.  V890 Aql was the minor planet (258) Tyche;  setting the 'class' to mp and the 'obscure cross-ID' to (258) Tyche should get that point across.  And so on.

I am content to "lose" the information that T Sco is in M80.  [I've put together a draft version modifying the above cases](https://www.projectpluto.com/temp/galnovae.txt) which,  I think,  addresses each of the above problems.  I'll give it another look tomorrow (getting late here!) and finish it up.

**Comment by aaguasca** [comment]
Thank you for the explanation! I took a look at the draft version, and it seems fine.

> I am content to "lose" the information that T Sco is in M80

Perhaps you could add "In M80" in the "OBSCURE XID" column as you have done for N Oph 1938 in the draft version. Maybe like "N Sco No.1. In M80".
